#FILE TO GET SETTED SMTP PASSWORD


#COMMAND FOR SETTING PASSWORD 
# $env:SMTP_PASSWORD = "KAUSHAL;
# COMMAND TO CHECK PASSWORD IS SET OR NOT
# $env:SMTP_PASSWORD 
import os
print(os.getenv("SMTP_PASSWORD"))  